/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package academia;

/**
 *
 * @author eletro
 */
public class CadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        Cadastros01_campo_senha = new javax.swing.JLabel();
        Cadastros01_txtcampo_senha = new javax.swing.JTextField();
        Cadastros01_campo_data_admissao = new javax.swing.JLabel();
        Cadastros01_campo_data_demissao = new javax.swing.JLabel();
        Cadastros01_txtcampo_data_admissao = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        Cadastros01_txtcampo_profissao = new javax.swing.JTextField();
        Cadastros01_campo_profissao = new javax.swing.JLabel();
        Cadastros01_txtcampo_numero_socio = new javax.swing.JTextField();
        Cadastros01_campo_numero_socio = new javax.swing.JLabel();
        Cadastros01_txtcampo_CPF = new javax.swing.JTextField();
        Cadastros01_txtcampo_email = new javax.swing.JTextField();
        Cadastros01_campo_CPF = new javax.swing.JLabel();
        Cadastros01_txtcampo_idade = new javax.swing.JTextField();
        Cadastros01_campo_idade = new javax.swing.JLabel();
        Cadastros01_campo_telefone = new javax.swing.JLabel();
        Cadastros01_campo_estado_civil = new javax.swing.JComboBox();
        Cadastros01_campo_sexo = new javax.swing.JComboBox();
        Cadastros01_campo_email = new javax.swing.JLabel();
        Cadastros01_campo_nome = new javax.swing.JLabel();
        Cadastros01_txtcampo_nome = new javax.swing.JTextField();
        Cadastros01_campo_especificacao_do_socio = new javax.swing.JLabel();
        Cadastros01_txtcampo_especificacao_do_socio = new javax.swing.JTextField();
        Cadastros01_txtcampo_telefone = new javax.swing.JFormattedTextField();
        Cadastros01_campo_botao_limpar = new javax.swing.JButton();
        Cadastros01_campo_botao_finalizar_cadastro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Cadastros01_campo_cidade = new javax.swing.JLabel();
        Cadastros01_campo_bairro = new javax.swing.JLabel();
        Cadastros01_campo_estados_brasileiros = new javax.swing.JComboBox();
        Cadastros01_campo_rua = new javax.swing.JLabel();
        Cadastros01_txtcampo_cidade = new javax.swing.JTextField();
        Cadastros01_txtcampo_bairro = new javax.swing.JTextField();
        Cadastros01_txtcampo_rua = new javax.swing.JTextField();
        Cadastros01_campo_CEP = new javax.swing.JLabel();
        Cadastros01_txtcampo_CEP = new javax.swing.JFormattedTextField();
        Cadastros01_campo_botao_sair = new javax.swing.JButton();
        Cadastros01_campo_confirmação = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Cadastros01_txtcampo_telefone1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        Cadastros01_campo_estados_brasileiros1 = new javax.swing.JComboBox();
        Cadastros01_txtcampo_CEP1 = new javax.swing.JFormattedTextField();
        Cadastros01_txtcampo_bairro1 = new javax.swing.JTextField();
        Cadastros01_campo_CEP1 = new javax.swing.JLabel();
        Cadastros01_txtcampo_rua1 = new javax.swing.JTextField();
        Cadastros01_campo_bairro1 = new javax.swing.JLabel();
        Cadastros01_campo_rua1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Associado"));

        Cadastros01_campo_senha.setText("Senha:");

        Cadastros01_campo_data_admissao.setText("Data de emissão:");

        Cadastros01_campo_data_demissao.setText("Data de demissão:");

        try {
            Cadastros01_txtcampo_data_admissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_txtcampo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addComponent(Cadastros01_campo_data_admissao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Cadastros01_txtcampo_data_admissao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addComponent(Cadastros01_campo_data_demissao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_senha)
                    .addComponent(Cadastros01_txtcampo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_data_admissao)
                    .addComponent(Cadastros01_txtcampo_data_admissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_data_demissao)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações pessoais"));

        Cadastros01_txtcampo_profissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastros01_txtcampo_profissaoActionPerformed(evt);
            }
        });

        Cadastros01_campo_profissao.setText("Profissão:");

        Cadastros01_txtcampo_numero_socio.setBackground(new java.awt.Color(204, 204, 204));

        Cadastros01_campo_numero_socio.setText("N° socio:");

        Cadastros01_campo_CPF.setText("CPF:");

        Cadastros01_txtcampo_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastros01_txtcampo_idadeActionPerformed(evt);
            }
        });

        Cadastros01_campo_idade.setText("Idade:");

        Cadastros01_campo_telefone.setText("Telefone:");

        Cadastros01_campo_estado_civil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado Civil", "Solteiro", "Casado" }));

        Cadastros01_campo_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sexo", "Feminino", "Masculino" }));

        Cadastros01_campo_email.setText("Email:");

        Cadastros01_campo_nome.setText("Nome:");

        Cadastros01_campo_especificacao_do_socio.setText("Especificação do sócio:");

        try {
            Cadastros01_txtcampo_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_especificacao_do_socio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_txtcampo_especificacao_do_socio))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(Cadastros01_campo_profissao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Cadastros01_txtcampo_profissao))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(Cadastros01_campo_email)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Cadastros01_txtcampo_email))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(Cadastros01_campo_telefone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Cadastros01_txtcampo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Cadastros01_campo_CPF)
                                    .addGap(3, 3, 3)
                                    .addComponent(Cadastros01_txtcampo_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Cadastros01_campo_nome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cadastros01_txtcampo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Cadastros01_campo_numero_socio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cadastros01_txtcampo_numero_socio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Cadastros01_campo_idade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cadastros01_txtcampo_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Cadastros01_campo_estado_civil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cadastros01_campo_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cadastros01_txtcampo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cadastros01_campo_nome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cadastros01_campo_idade)
                            .addComponent(Cadastros01_txtcampo_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cadastros01_campo_numero_socio)
                            .addComponent(Cadastros01_txtcampo_numero_socio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Cadastros01_campo_estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_telefone)
                    .addComponent(Cadastros01_campo_CPF)
                    .addComponent(Cadastros01_txtcampo_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cadastros01_txtcampo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_profissao)
                    .addComponent(Cadastros01_txtcampo_profissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_txtcampo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cadastros01_campo_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_especificacao_do_socio)
                    .addComponent(Cadastros01_txtcampo_especificacao_do_socio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cadastros01_campo_botao_limpar.setText("Limpar");
        Cadastros01_campo_botao_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastros01_campo_botao_limparActionPerformed(evt);
            }
        });

        Cadastros01_campo_botao_finalizar_cadastro.setText("Finalizar Cadastro");
        Cadastros01_campo_botao_finalizar_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastros01_campo_botao_finalizar_cadastroActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        Cadastros01_campo_cidade.setText("Cidade:");

        Cadastros01_campo_bairro.setText("Bairro:");

        Cadastros01_campo_estados_brasileiros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estados Brasileiros", "AC- Acre ", "AL- Alagoas ", "AP- Amapá \t", "AM- Amazonas  \t", "BA- Bahia\t", "CE- Ceará  \t", "DF- Distrito Federal \t", "ES- Espírito Santo ", "GO- Goiás  ", "MA- Maranhão \t", "MT-Mato Grosso \t", "MS- Mato Grosso do Sul \t \t", "MG- Minas Gerais \t", "PR- Paraná ", "PA- Pará \t", "PE- Pernambuco", "PI- Piauí \t", "RJ- Rio de Janeiro \t", "RN- Rio Grande do Norte \t", "RS- Rio Grande do Sul \t", "RO- Rondonia \t", "RR- Roraima \t", "SC- Santa Catarina \t", "SE- Sergipe \t", "SP- São Paulo \t", "TO- Tocantins \t", " " }));

        Cadastros01_campo_rua.setText("Rua:");

        Cadastros01_campo_CEP.setText("CEP:");

        try {
            Cadastros01_txtcampo_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_txtcampo_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_rua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_txtcampo_rua)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cadastros01_campo_estados_brasileiros, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_CEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_txtcampo_CEP)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Cadastros01_campo_bairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cadastros01_txtcampo_bairro))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_cidade)
                    .addComponent(Cadastros01_txtcampo_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cadastros01_campo_estados_brasileiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_rua)
                    .addComponent(Cadastros01_txtcampo_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cadastros01_campo_CEP)
                    .addComponent(Cadastros01_txtcampo_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_bairro)
                    .addComponent(Cadastros01_txtcampo_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cadastros01_campo_botao_sair.setText("Sair");
        Cadastros01_campo_botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastros01_campo_botao_sairActionPerformed(evt);
            }
        });

        Cadastros01_campo_confirmação.setForeground(new java.awt.Color(255, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados pessoais"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Idade:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone:");

        try {
            Cadastros01_txtcampo_telefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("CPF:");

        jLabel5.setText("Registo geral:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Código");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sexo", "Masculino", "Feminino" }));

        jLabel7.setText("Data de nascimento:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setText("Status:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Desativo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cadastros01_txtcampo_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(Cadastros01_txtcampo_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel8.setText("Cidade:");

        Cadastros01_campo_estados_brasileiros1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estados Brasileiros", "AC- Acre ", "AL- Alagoas ", "AP- Amapá \t", "AM- Amazonas  \t", "BA- Bahia\t", "CE- Ceará  \t", "DF- Distrito Federal \t", "ES- Espírito Santo ", "GO- Goiás  ", "MA- Maranhão \t", "MT-Mato Grosso \t", "MS- Mato Grosso do Sul \t \t", "MG- Minas Gerais \t", "PR- Paraná ", "PA- Pará \t", "PE- Pernambuco", "PI- Piauí \t", "RJ- Rio de Janeiro \t", "RN- Rio Grande do Norte \t", "RS- Rio Grande do Sul \t", "RO- Rondonia \t", "RR- Roraima \t", "SC- Santa Catarina \t", "SE- Sergipe \t", "SP- São Paulo \t", "TO- Tocantins \t", " " }));

        try {
            Cadastros01_txtcampo_CEP1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Cadastros01_campo_CEP1.setText("CEP:");

        Cadastros01_campo_bairro1.setText("Bairro:");

        Cadastros01_campo_rua1.setText("Rua:");

        jLabel9.setText("Logradouro:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_CEP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cadastros01_txtcampo_CEP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_campo_bairro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_txtcampo_bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastros01_campo_estados_brasileiros1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Cadastros01_campo_rua1)
                        .addGap(18, 18, 18)
                        .addComponent(Cadastros01_txtcampo_rua1)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cadastros01_campo_estados_brasileiros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_rua1)
                    .addComponent(Cadastros01_txtcampo_rua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastros01_campo_CEP1)
                    .addComponent(Cadastros01_txtcampo_CEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cadastros01_campo_bairro1)
                    .addComponent(Cadastros01_txtcampo_bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fisico"));

        jLabel10.setText("Altura:");

        jLabel11.setText("Peso:");

        jLabel12.setText("Modalidade:");

        jLabel13.setText("Professor:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deletar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastros01_txtcampo_profissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastros01_txtcampo_profissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cadastros01_txtcampo_profissaoActionPerformed

    private void Cadastros01_txtcampo_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastros01_txtcampo_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cadastros01_txtcampo_idadeActionPerformed

    private void Cadastros01_campo_botao_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastros01_campo_botao_limparActionPerformed
        // TODO
    }//GEN-LAST:event_Cadastros01_campo_botao_limparActionPerformed

    private void Cadastros01_campo_botao_finalizar_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastros01_campo_botao_finalizar_cadastroActionPerformed
        if (Cadastros01_txtcampo_nome.getText().equals("")) {
            Cadastros01_txtcampo_nome.grabFocus();
            Cadastros01_txtcampo_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_numero_socio.getText().equals("")) {
            Cadastros01_txtcampo_numero_socio.grabFocus();
            Cadastros01_txtcampo_numero_socio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_idade.getText().equals("")) {
            Cadastros01_txtcampo_idade.grabFocus();
            Cadastros01_txtcampo_idade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_telefone.getText().equals("")) {
            Cadastros01_txtcampo_telefone.grabFocus();
            Cadastros01_txtcampo_telefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_CPF.getText().equals("")) {
            Cadastros01_txtcampo_CPF.grabFocus();
            Cadastros01_txtcampo_CPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_profissao.getText().equals("")) {
            Cadastros01_txtcampo_profissao.grabFocus();
            Cadastros01_txtcampo_profissao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_especificacao_do_socio.getText().equals("")) {
            Cadastros01_txtcampo_especificacao_do_socio.grabFocus();
            Cadastros01_txtcampo_especificacao_do_socio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_cidade.getText().equals("")) {
            Cadastros01_txtcampo_cidade.grabFocus();
            Cadastros01_txtcampo_cidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_rua.getText().equals("")) {
            Cadastros01_txtcampo_rua.grabFocus();
            Cadastros01_txtcampo_rua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_CEP.getText().equals("")) {
            Cadastros01_txtcampo_CEP.grabFocus();
            Cadastros01_txtcampo_CEP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_bairro.getText().equals("")) {
            Cadastros01_txtcampo_bairro.grabFocus();
            Cadastros01_txtcampo_bairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_senha.getText().equals("")) {
            Cadastros01_txtcampo_senha.grabFocus();
            Cadastros01_txtcampo_senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }
        if (Cadastros01_txtcampo_data_admissao.getText().equals("")) {
            Cadastros01_txtcampo_data_admissao.grabFocus();
            Cadastros01_txtcampo_data_admissao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
            Cadastros01_campo_confirmação.setText("Campos em vermelho são obrigatorio");
        }else {
            Cadastros01_campo_confirmação.setText("     Cadastro realizado com sucesso");
        }

    }//GEN-LAST:event_Cadastros01_campo_botao_finalizar_cadastroActionPerformed

    private void Cadastros01_campo_botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastros01_campo_botao_sairActionPerformed
        dispose();
    }//GEN-LAST:event_Cadastros01_campo_botao_sairActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cadastros01_campo_CEP;
    private javax.swing.JLabel Cadastros01_campo_CEP1;
    private javax.swing.JLabel Cadastros01_campo_CPF;
    private javax.swing.JLabel Cadastros01_campo_bairro;
    private javax.swing.JLabel Cadastros01_campo_bairro1;
    private javax.swing.JButton Cadastros01_campo_botao_finalizar_cadastro;
    private javax.swing.JButton Cadastros01_campo_botao_limpar;
    private javax.swing.JButton Cadastros01_campo_botao_sair;
    private javax.swing.JLabel Cadastros01_campo_cidade;
    private javax.swing.JLabel Cadastros01_campo_confirmação;
    private javax.swing.JLabel Cadastros01_campo_data_admissao;
    private javax.swing.JLabel Cadastros01_campo_data_demissao;
    private javax.swing.JLabel Cadastros01_campo_email;
    private javax.swing.JLabel Cadastros01_campo_especificacao_do_socio;
    private javax.swing.JComboBox Cadastros01_campo_estado_civil;
    private javax.swing.JComboBox Cadastros01_campo_estados_brasileiros;
    private javax.swing.JComboBox Cadastros01_campo_estados_brasileiros1;
    private javax.swing.JLabel Cadastros01_campo_idade;
    private javax.swing.JLabel Cadastros01_campo_nome;
    private javax.swing.JLabel Cadastros01_campo_numero_socio;
    private javax.swing.JLabel Cadastros01_campo_profissao;
    private javax.swing.JLabel Cadastros01_campo_rua;
    private javax.swing.JLabel Cadastros01_campo_rua1;
    private javax.swing.JLabel Cadastros01_campo_senha;
    private javax.swing.JComboBox Cadastros01_campo_sexo;
    private javax.swing.JLabel Cadastros01_campo_telefone;
    private javax.swing.JFormattedTextField Cadastros01_txtcampo_CEP;
    private javax.swing.JFormattedTextField Cadastros01_txtcampo_CEP1;
    private javax.swing.JTextField Cadastros01_txtcampo_CPF;
    private javax.swing.JTextField Cadastros01_txtcampo_bairro;
    private javax.swing.JTextField Cadastros01_txtcampo_bairro1;
    private javax.swing.JTextField Cadastros01_txtcampo_cidade;
    private javax.swing.JFormattedTextField Cadastros01_txtcampo_data_admissao;
    private javax.swing.JTextField Cadastros01_txtcampo_email;
    private javax.swing.JTextField Cadastros01_txtcampo_especificacao_do_socio;
    private javax.swing.JTextField Cadastros01_txtcampo_idade;
    private javax.swing.JTextField Cadastros01_txtcampo_nome;
    private javax.swing.JTextField Cadastros01_txtcampo_numero_socio;
    private javax.swing.JTextField Cadastros01_txtcampo_profissao;
    private javax.swing.JTextField Cadastros01_txtcampo_rua;
    private javax.swing.JTextField Cadastros01_txtcampo_rua1;
    private javax.swing.JTextField Cadastros01_txtcampo_senha;
    private javax.swing.JFormattedTextField Cadastros01_txtcampo_telefone;
    private javax.swing.JFormattedTextField Cadastros01_txtcampo_telefone1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
