/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package academia;

import javax.swing.JOptionPane;

/**
 *
 * @author eletro
 */
public class Login01 extends javax.swing.JFrame {

    /**
     * Creates new form Login01
     */
    public Login01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_campo_txtlogin = new javax.swing.JTextField();
        campo_botao_login = new javax.swing.JButton();
        Login_campo_txtsenha = new javax.swing.JPasswordField();
        Login_campo_senha = new javax.swing.JLabel();
        Login_campo_login = new javax.swing.JLabel();
        campo_botao_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campo_botao_login.setText("LOGIN");
        campo_botao_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_botao_loginActionPerformed(evt);
            }
        });
        campo_botao_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_botao_loginKeyPressed(evt);
            }
        });

        Login_campo_senha.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        Login_campo_senha.setText("SENHA");

        Login_campo_login.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        Login_campo_login.setText("LOGIN");

        campo_botao_sair.setText("SAIR");
        campo_botao_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo_botao_sairMousePressed(evt);
            }
        });
        campo_botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_botao_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(Login_campo_senha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Login_campo_login))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Login_campo_txtlogin)
                        .addComponent(Login_campo_txtsenha)
                        .addComponent(campo_botao_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campo_botao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Login_campo_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_campo_txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(Login_campo_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_campo_txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(campo_botao_login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_botao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campo_botao_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_botao_loginActionPerformed
        if (Login_campo_txtlogin.getText().equals("admin") && (Login_campo_txtsenha.getText().equals("1311"))) {
            new Menu01().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Login ou senha errado! Tente novamente");
        }
    }//GEN-LAST:event_campo_botao_loginActionPerformed

    private void campo_botao_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_botao_loginKeyPressed

    }//GEN-LAST:event_campo_botao_loginKeyPressed

    private void campo_botao_sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_botao_sairMousePressed
        dispose();
    }//GEN-LAST:event_campo_botao_sairMousePressed

    private void campo_botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_botao_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_botao_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_campo_login;
    private javax.swing.JLabel Login_campo_senha;
    private javax.swing.JTextField Login_campo_txtlogin;
    private javax.swing.JPasswordField Login_campo_txtsenha;
    private javax.swing.JButton campo_botao_login;
    private javax.swing.JButton campo_botao_sair;
    // End of variables declaration//GEN-END:variables
}
